language: node_js
node_js:
  - "12.13.0"
branches:
  only:
    - master
install:
  - yarn install
cache:
  yarn: true
  directories:
    - node_modules
script:
  - CI=true yarn build
  - CI=true yarn coverage # included test
# Send coverage data to Coveralls
after_script: # Upload coverage reports
  - COVERALLS_REPO_TOKEN=$coveralls_repo_token yarn run coveralls
