language: node_js
node_js:
  - "11.10.1"
install:
  - yarn install
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn build
  - yarn coverage # included test
# Send coverage data to Coveralls
after_script: # Upload coverage reports
  - COVERALLS_REPO_TOKEN=$coveralls_repo_token yarn run coveralls
