"use strict";
var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
Object.defineProperty(exports, "__esModule", { value: true });
var styled_1 = require("../../../utils/styled");
var colors_1 = require("../../../common/colors");
exports.Root = styled_1.default.div(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n  font-family: ", ";\n\n  h1,\n  h2,\n  h3,\n  h4,\n  h5,\n  h6 {\n    font-weight: 500;\n    line-height: 1.25;\n    margin-bottom: 0.5em;\n    margin-top: 0;\n  }\n\n  h1,\n  h2,\n  h3,\n  h4 {\n    color: ", ";\n  }\n\n  h5,\n  h6 {\n    color: ", ";\n  }\n\n  p {\n    color: ", ";\n    line-height: 1.5;\n    margin-bottom: 0.5em;\n    margin-top: 0;\n  }\n\n  a {\n    color: ", ";\n    outline: none;\n    text-decoration: none;\n\n    &:hover {\n      color: ", ";\n    }\n\n    &:focus,\n    &:hover,\n    &:active {\n      text-decoration: underline;\n    }\n    &:focus,\n    &:active {\n      color: ", ";\n    }\n    &:focus {\n      text-decoration: none;\n    }\n  }\n\n  b,\n  strong {\n    font-weight: bolder;\n  }\n\n  code,\n  kbd,\n  pre,\n  samp {\n    font-family: \"Menlo, Courier, monospace\";\n  }\n\n  code {\n    color: ", ";\n    background: ", ";\n    padding: 0.1rem 0.15rem;\n    line-height: 1.2;\n  }\n"], ["\n  font-family: ", ";\n\n  h1,\n  h2,\n  h3,\n  h4,\n  h5,\n  h6 {\n    font-weight: 500;\n    line-height: 1.25;\n    margin-bottom: 0.5em;\n    margin-top: 0;\n  }\n\n  h1,\n  h2,\n  h3,\n  h4 {\n    color: ", ";\n  }\n\n  h5,\n  h6 {\n    color: ", ";\n  }\n\n  p {\n    color: ", ";\n    line-height: 1.5;\n    margin-bottom: 0.5em;\n    margin-top: 0;\n  }\n\n  a {\n    color: ", ";\n    outline: none;\n    text-decoration: none;\n\n    &:hover {\n      color: ", ";\n    }\n\n    &:focus,\n    &:hover,\n    &:active {\n      text-decoration: underline;\n    }\n    &:focus,\n    &:active {\n      color: ", ";\n    }\n    &:focus {\n      text-decoration: none;\n    }\n  }\n\n  b,\n  strong {\n    font-weight: bolder;\n  }\n\n  code,\n  kbd,\n  pre,\n  samp {\n    font-family: \"Menlo, Courier, monospace\";\n  }\n\n  code {\n    color: ", ";\n    background: ", ";\n    padding: 0.1rem 0.15rem;\n    line-height: 1.2;\n  }\n"])), function (props) { return props.theme.fonts; }, colors_1.colors.N90, colors_1.colors.N80, colors_1.colors.N70, colors_1.colors.B50, colors_1.colors.B30, colors_1.colors.B60, colors_1.colors.R20, colors_1.colors.N1);
exports.Root.displayName = "Root";
exports.default = exports.Root;
var templateObject_1;
//# sourceMappingURL=Root.js.map